import type { Metadata } from "next";
// import { GeistSans, GeistMono } from "@vercel/font-geist"; // Explicitly import GeistSans and GeistMono
import "./globals.css";
import { Toaster } from "sonner"; // Import Toaster
import { ThemeProvider } from "next-themes"; // Import ThemeProvider
import { Suspense } from "react"; // Import Suspense for potential future use
import dynamic from "next/dynamic"; // Import dynamic for client-side only component loading

// Dynamically import GlobalLoadingIndicator with ssr: false
const GlobalLoadingIndicator = dynamic(() => import("@/components/GlobalLoadingIndicator").then(mod => mod.GlobalLoadingIndicator), { ssr: false });

// const geistSans = GeistSans({ // Use GeistSans directly
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = GeistMono({ // Use GeistMono directly
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <GlobalLoadingIndicator /> {/* Add GlobalLoadingIndicator here */}
          {children}
          <Toaster richColors position="top-center" /> {/* Add Toaster here */}
        </ThemeProvider>
      </body>
    </html>
  );
}