// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uhkihabnagsumxxhltzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoa2loYWJuYWdzdW14eGhsdHpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzMTg1NzQsImV4cCI6MjA3Njg5NDU3NH0.jPovMDnVUQfFblKxWyRzFkikaI9W4VfkmSgGTo24HhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);